---
Description: 'AWS CloudFormation Sample Template: This template demonstrates the creation
  of a DynamoDB table.'
Parameters:
  TableName:
      Description: "The DynamoDB table name"
      Type: String
      Default: rhystest-table  # lower case alpha numeric and hyphens? TODO AllowedPattern

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
      - AttributeName: 'id'
        AttributeType: 'S'
      - AttributeName: 'timestamp'
        AttributeType: 'N'
      KeySchema:
      - AttributeName: 'id'
        KeyType: 'HASH'
      - AttributeName: 'timestamp'
        KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: 50
        WriteCapacityUnits: 50
      StreamSpecification:
        StreamViewType: 'NEW_IMAGE'

Outputs:  
  TableStreamArn:
    Description: Table Stream arn of the newly create DynamoDB table
    Value: !GetAtt DynamoDBTable.StreamArn
    Export:
      Name: !Sub "${TableName}-dynamodb-stream-arn"
