AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  FeaturePrefix:
      Description: "The name to be used to prefix resources"
      Type: String
      Default: rhystest  # lower case alpha numeric and hyphens? TODO AllowedPattern

Resources:

  S3EventsBucketName:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join # lower case alpha numeric and hyphens
          - ""
          -
            - Ref: FeaturePrefix
            - "-firehose-bucket"
      VersioningConfiguration:
        Status: Suspended

  DataFirehoseToS3Role:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Join
          - ""
          -
            - !Ref FeaturePrefix
            - "FirehoseToS3Role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "firehose.amazonaws.com"
            Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId":
                  Ref: "AWS::AccountId"
      Policies:
        -
          PolicyName: !Join
              - ""
              -
                - !Ref FeaturePrefix
                - "FirehoseToS3Policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:AbortMultipartUpload"
                  - "s3:GetBucketLocation"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                  - "s3:ListBucketMultipartUploads"
                Resource:
                  - !Join
                    - ""
                    - - "arn:aws:s3:::"
                      - !Ref S3EventsBucketName
                  - Fn::Join:
                    - ""
                    - - "arn:aws:s3:::"
                      - !Ref S3EventsBucketName
                      - "/*"
              # -
              #   Effect: "Allow"
              #   Action:
              #     - "kms:Decrypt",
              #     - "kms:GenerateDataKey"
              #   Resource:
              #     - Fn::Join:
              #       - ""
              #       - - "arn:aws:kms:"
              #         - Ref: "AWS::Region"
              #         - ":"
              #         - Ref: "AWS::AccountId"
              #         - ":key/"
              #         - Ref: AwsKeyId
              #   Condition:
              #     StringEquals:
              #       "kms:ViaService":
              #         Fn::Join:
              #           - ""
              #           - - "s3."
              #             - !Ref "AWS::Region"
              #             - ".amazonaws.com"
              #     StringEquals:
              #       "kms:EncryptionContext:aws:s3:arn":
              #         Fn::Join:
              #           - ""
              #           - - "arn:aws:s3:::"
              #             - !Ref S3EventsBucketName
              #             - "/*"
              #
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

  DataFirehoseStream:
    Type: "AWS::KinesisFirehose::DeliveryStream"
    Properties:
      DeliveryStreamName: !Join
        - ""
        -
          - Ref: FeaturePrefix
          - "-firehose"
      S3DestinationConfiguration:
        BucketARN: !Join
          - ''
          - - 'arn:aws:s3:::'
            - Ref: S3EventsBucketName
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 2
        CompressionFormat: UNCOMPRESSED #GZIP
        Prefix: "" # I dont think we should default a prefix, unless we decide to share buckets
        RoleARN: !GetAtt ["DataFirehoseToS3Role", "Arn"]
        #EncryptionConfiguration:  EncryptionConfiguration - we can do this when we can manage keys

Outputs:

  DataStreamFirehoseOutput:
    Description: "The event kinesis firehose stream"
    Value: !Ref DataFirehoseStream
    Export:
      Name: !Sub "${FeaturePrefix}-event-kinesis-firehose"
  DataStreamFirehoseArnOutput:
    Description: "The event kinesis firehose stream ARN"
    Value: !Join
        - ""
        - - "arn:aws:firehose:"
          - Ref: "AWS::Region"
          - ":"
          - Ref: "AWS::AccountId"
          - ":deliverystream/"
          - !Ref DataFirehoseStream
    Export:
      Name: !Sub "${FeaturePrefix}-event-kinesis-firehose-arn"
  EventS3BucketOutput:
    Description: "The s3 bucket that will make up part of your data lake"
    Value: !Ref S3EventsBucketName
    Export:
      Name: !Sub "${FeaturePrefix}-event-s3-bucket"
